namespace Backend.Models;

// This class = one row in the Users table
// Each property = one column
public class User
{
    // Id is auto-generated by PostgreSQL (SERIAL)
    // You never set this manually
    public int Id { get; set; }

    // = '' means default empty string (avoids null warnings)
    public string Name  { get; set; } = "";
    public string Email { get; set; } = "";
    public string Phone { get; set; } = "";
    public string City  { get; set; } = "";
}
